version: 2.1
jobs:
  build:
    working_directory: ~/jsonplaceholder-api-testing
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew test
